-- ============================================================================
-- Kelmon Fashion — initial schema
--
-- Firebase Auth issues identity; Supabase Postgres holds the data and enforces
-- access through Row Level Security. A user id is a Firebase UID (a 28-character
-- string), so identity columns are `text` and there is no `auth.users` anywhere.
--
-- This file has two halves:
--
--   1. DDL generated by `prisma migrate diff --from-empty --to-schema`, pasted
--      verbatim. Do not hand-edit it — change prisma/schema.prisma and
--      regenerate, or the schema and the migration silently diverge.
--
--   2. Everything Prisma cannot express: CHECK constraints, partial indexes,
--      functions, triggers, RLS policies and storage buckets. Hand-written, and
--      the reason this migration is worth reading.
--
-- This supersedes the earlier supabase/migrations/0001-0003, which were written
-- before Prisma owned the schema. They are collapsed into this one file because
-- the database was still empty, so there was no history worth preserving.
-- ============================================================================

-- gen_random_uuid() comes from pgcrypto, and the tables below default to it, so
-- this has to run first. Prisma's generated DDL does not include it.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. Generated by Prisma — do not hand-edit
-- ============================================================================

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "user_role" AS ENUM ('customer', 'admin');

-- CreateEnum
CREATE TYPE "order_status" AS ENUM ('pending', 'awaiting_mpesa', 'confirmed', 'packed', 'delivered', 'cancelled');

-- CreateEnum
CREATE TYPE "payment_status" AS ENUM ('unpaid', 'initiated', 'paid', 'failed');

-- CreateEnum
CREATE TYPE "payment_method" AS ENUM ('mpesa', 'cod');

-- CreateEnum
CREATE TYPE "order_source" AS ENUM ('storefront', 'admin_direct');

-- CreateTable
CREATE TABLE "profiles" (
    "id" TEXT NOT NULL,
    "email" TEXT,
    "full_name" TEXT,
    "phone" TEXT,
    "campus" TEXT,
    "avatar_url" TEXT,
    "role" "user_role" NOT NULL DEFAULT 'customer',
    "loyalty_points" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "products" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "price" DECIMAL(10,2) NOT NULL,
    "original_price" DECIMAL(10,2),
    "category" TEXT NOT NULL,
    "images" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "sizes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "colors" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "stock" INTEGER NOT NULL DEFAULT 0,
    "rating" DECIMAL(2,1) NOT NULL DEFAULT 0,
    "review_count" INTEGER NOT NULL DEFAULT 0,
    "badge" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "orders" (
    "id" TEXT NOT NULL,
    "user_id" TEXT,
    "customer_name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "drop_point" TEXT NOT NULL,
    "campus" TEXT,
    "notes" TEXT,
    "payment_method" "payment_method" NOT NULL DEFAULT 'mpesa',
    "subtotal" DECIMAL(10,2) NOT NULL,
    "delivery_fee" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "total" DECIMAL(10,2) NOT NULL,
    "status" "order_status" NOT NULL DEFAULT 'pending',
    "payment_status" "payment_status" NOT NULL DEFAULT 'unpaid',
    "source" "order_source" NOT NULL DEFAULT 'storefront',
    "mpesa_checkout_request_id" TEXT,
    "mpesa_merchant_request_id" TEXT,
    "mpesa_receipt_number" TEXT,
    "mpesa_result_desc" TEXT,
    "mpesa_phone" TEXT,
    "points_awarded" BOOLEAN NOT NULL DEFAULT false,
    "points_earned" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "order_id" TEXT NOT NULL,
    "product_id" TEXT,
    "name" TEXT NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "quantity" INTEGER NOT NULL,
    "variant" TEXT,
    "image" TEXT,
    "category" TEXT,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reviews" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" TEXT,
    "product_id" TEXT,
    "author_name" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "body" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "deals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" TEXT NOT NULL,
    "description" TEXT,
    "image" TEXT,
    "code" TEXT,
    "discount_percent" INTEGER,
    "starts_at" TIMESTAMPTZ(6),
    "ends_at" TIMESTAMPTZ(6),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "deals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "updates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "tag" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "updates_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "orders_user_created_idx" ON "orders"("user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "orders_created_idx" ON "orders"("created_at" DESC);

-- CreateIndex
CREATE INDEX "orders_status_idx" ON "orders"("status");

-- CreateIndex
CREATE INDEX "orders_payment_status_idx" ON "orders"("payment_status");

-- CreateIndex
CREATE INDEX "order_items_order_idx" ON "order_items"("order_id");

-- CreateIndex
CREATE INDEX "reviews_product_idx" ON "reviews"("product_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "reviews_created_idx" ON "reviews"("created_at" DESC);

-- CreateIndex
CREATE INDEX "deals_created_idx" ON "deals"("created_at" DESC);

-- CreateIndex
CREATE INDEX "updates_created_idx" ON "updates"("created_at" DESC);

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================================
-- 2. Hand-written: what Prisma cannot express
-- ============================================================================

-- ── Array columns are never null, only empty ────────────────────────────────
-- Prisma models a scalar list as non-nullable but emits no NOT NULL, which
-- leaves `images IS NULL` possible and forces every reader to handle two empty
-- cases. One is enough.

ALTER TABLE "products" ALTER COLUMN "images" SET NOT NULL;
ALTER TABLE "products" ALTER COLUMN "sizes"  SET NOT NULL;
ALTER TABLE "products" ALTER COLUMN "colors" SET NOT NULL;

-- ── CHECK constraints ───────────────────────────────────────────────────────
-- Prisma has no syntax for these, and they are the difference between a schema
-- that documents intent and one that enforces it.

ALTER TABLE "profiles"
  ADD CONSTRAINT profiles_loyalty_points_non_negative CHECK (loyalty_points >= 0);

ALTER TABLE "products"
  ADD CONSTRAINT products_price_non_negative CHECK (price >= 0),
  -- A "was" price that is not higher than the current one is not a discount.
  ADD CONSTRAINT products_original_price_higher CHECK (original_price IS NULL OR original_price >= price),
  ADD CONSTRAINT products_stock_non_negative CHECK (stock >= 0),
  ADD CONSTRAINT products_rating_range CHECK (rating BETWEEN 0 AND 5),
  ADD CONSTRAINT products_review_count_non_negative CHECK (review_count >= 0);

ALTER TABLE "orders"
  ADD CONSTRAINT orders_subtotal_non_negative CHECK (subtotal >= 0),
  ADD CONSTRAINT orders_delivery_fee_non_negative CHECK (delivery_fee >= 0),
  ADD CONSTRAINT orders_total_non_negative CHECK (total >= 0);

ALTER TABLE "order_items"
  ADD CONSTRAINT order_items_price_non_negative CHECK (price >= 0),
  ADD CONSTRAINT order_items_quantity_positive CHECK (quantity > 0);

ALTER TABLE "reviews"
  ADD CONSTRAINT reviews_rating_range CHECK (rating BETWEEN 1 AND 5);

ALTER TABLE "deals"
  ADD CONSTRAINT deals_discount_percent_range CHECK (discount_percent IS NULL OR discount_percent BETWEEN 1 AND 100),
  ADD CONSTRAINT deals_window_valid CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at);

-- ── Partial indexes ─────────────────────────────────────────────────────────
-- Prisma cannot put a WHERE clause on an index. Two of these are correctness,
-- not performance.

-- The storefront only ever queries active products, so the index should only
-- carry active rows.
CREATE INDEX products_category_idx ON "products" (category) WHERE active;
CREATE INDEX products_active_created_idx ON "products" (created_at DESC) WHERE active;

-- Correctness: the M-Pesa callback looks an order up by CheckoutRequestID. A
-- duplicate would make that lookup ambiguous and could mark the wrong order paid.
CREATE UNIQUE INDEX orders_mpesa_checkout_idx
  ON "orders" (mpesa_checkout_request_id)
  WHERE mpesa_checkout_request_id IS NOT NULL;

-- Correctness: one review per customer per product, so ratings cannot be padded.
-- Partial, because NULLs here mean "guest" or "detached", not "same key".
CREATE UNIQUE INDEX reviews_user_product_idx
  ON "reviews" (user_id, product_id)
  WHERE user_id IS NOT NULL AND product_id IS NOT NULL;

-- ── Column documentation ────────────────────────────────────────────────────

COMMENT ON COLUMN "profiles"."id" IS
  'Firebase Auth UID. Created by app/api/auth/session/route.ts on first sign-in. Not a uuid, and there is no auth.users row behind it.';
COMMENT ON COLUMN "profiles"."loyalty_points" IS
  'Kelmon Points. Only award_loyalty_points() and redeem_loyalty_points() may change this.';
COMMENT ON COLUMN "products"."rating" IS
  'Derived. Maintained by sync_product_rating(); do not write by hand.';
COMMENT ON COLUMN "products"."review_count" IS
  'Derived. Maintained by sync_product_rating(); do not write by hand.';

-- ============================================================================
-- Identity and authorisation helpers
-- ============================================================================

-- The signed-in Firebase UID, or null.
--
-- `auth.uid()` casts the `sub` claim to uuid and a Firebase UID is not one, so
-- every policy below uses this instead. Reads the JWT claims straight from the
-- GUC rather than via auth.jwt(), so it does not depend on the auth schema.
--
-- Returns null when unauthenticated, and `column = null` is never true — so an
-- anonymous caller matches no owner row. That is the right failure direction.
CREATE OR REPLACE FUNCTION public.app_uid()
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT nullif(
    coalesce(
      current_setting('request.jwt.claim.sub', true),
      nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub'
    ),
    ''
  );
$$;

-- The `admin` custom claim, written by the Firebase Admin SDK in
-- lib/firebase/admin.ts. It cannot be self-granted: setting it needs the
-- service-account private key.
CREATE OR REPLACE FUNCTION public.app_is_admin_claim()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT coalesce(
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'admin')::boolean,
    false
  );
$$;

-- True when the request runs with the Supabase service key, or as a superuser
-- during a migration or seed.
--
-- PostgREST switches role per request (`set local role authenticated` /
-- `service_role`), so current_user is the right thing to read — not session_user,
-- which stays the connection's authenticator role throughout.
CREATE OR REPLACE FUNCTION public.app_is_service()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT current_user IN ('service_role', 'postgres', 'supabase_admin');
$$;

-- Claim first, table second. The claim is already in the verified token, so the
-- common case costs no read; profiles.role covers the window between a grant and
-- the user's next token refresh, and is the record that survives re-minting.
--
-- SECURITY DEFINER is required: this reads `profiles`, which has its own RLS
-- policies that call this function. Without it, evaluating one would recurse.
-- The pinned search_path stops a caller shadowing `profiles` from a schema
-- earlier in their own path.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT public.app_is_admin_claim()
      OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = public.app_uid() AND role = 'admin'
      );
$$;

-- ============================================================================
-- Triggers
-- ============================================================================

-- Keep updated_at honest without trusting the client.
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  new.updated_at = now();
  RETURN new;
END;
$$;

CREATE TRIGGER profiles_touch BEFORE UPDATE ON "profiles" FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER products_touch BEFORE UPDATE ON "products" FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER orders_touch   BEFORE UPDATE ON "orders"   FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- profiles.role and profiles.loyalty_points are not the account holder's to
-- write. Postgres has no column-level RLS, so a trigger enforces it — and it
-- raises rather than letting a rejected write look like a no-op.
--
-- Deliberately SECURITY INVOKER (the default): app_is_service() compares
-- current_user, and inside a SECURITY DEFINER function that is the function's
-- owner rather than the caller, which would make this guard pass for everyone.
CREATE OR REPLACE FUNCTION public.guard_profile_columns()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF public.app_is_service() OR public.is_admin() THEN
    RETURN new;
  END IF;

  IF new.role IS DISTINCT FROM old.role THEN
    RAISE EXCEPTION 'profiles.role is not client-writable.';
  END IF;
  IF new.loyalty_points IS DISTINCT FROM old.loyalty_points THEN
    RAISE EXCEPTION 'profiles.loyalty_points is only changed by award_loyalty_points() and redeem_loyalty_points().';
  END IF;

  RETURN new;
END;
$$;

CREATE TRIGGER profiles_guard_columns
  BEFORE UPDATE ON "profiles"
  FOR EACH ROW EXECUTE FUNCTION public.guard_profile_columns();

-- Recompute a product's cached rating/review_count, so the storefront's Product
-- shape needs no join on every read.
CREATE OR REPLACE FUNCTION public.sync_product_rating()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target text := coalesce(new.product_id, old.product_id);
BEGIN
  IF target IS NULL THEN
    RETURN coalesce(new, old);
  END IF;

  UPDATE public.products p
  SET rating = coalesce(agg.avg_rating, 0),
      review_count = coalesce(agg.n, 0)
  FROM (
    SELECT round(avg(rating)::numeric, 1) AS avg_rating, count(*) AS n
    FROM public.reviews WHERE product_id = target
  ) agg
  WHERE p.id = target;

  RETURN coalesce(new, old);
END;
$$;

CREATE TRIGGER reviews_sync_product_rating
  AFTER INSERT OR UPDATE OR DELETE ON "reviews"
  FOR EACH ROW EXECUTE FUNCTION public.sync_product_rating();

-- ============================================================================
-- Loyalty points and order cancellation
--
-- These live in SQL because they are read-then-write races anywhere else. The
-- previous implementation awarded points from the browser, relying on a
-- `pointsAwarded` flag — two concurrent callbacks could both read false and both
-- award.
-- ============================================================================

-- Idempotent: takes FOR UPDATE on the order row, so a duplicate M-Pesa callback
-- cannot double-award.
--
-- Tiers are scaled for fashion prices, not the snack prices this was ported from.
CREATE OR REPLACE FUNCTION public.award_loyalty_points(p_order_id text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  o   orders;
  pts integer;
BEGIN
  SELECT * INTO o FROM orders WHERE id = p_order_id FOR UPDATE;

  IF NOT FOUND OR o.points_awarded OR o.user_id IS NULL THEN
    RETURN 0;
  END IF;
  IF o.payment_status <> 'paid' THEN
    RETURN 0;
  END IF;

  pts := CASE
    WHEN o.total >= 5000 THEN 50
    WHEN o.total >= 1000 THEN 20
    ELSE 5
  END;

  UPDATE orders
  SET points_awarded = true, points_earned = pts
  WHERE id = p_order_id;

  UPDATE profiles
  SET loyalty_points = loyalty_points + pts
  WHERE id = o.user_id;

  RETURN pts;
END;
$$;

-- The balance check and the decrement are one statement, so two concurrent
-- redemptions cannot both pass the check.
CREATE OR REPLACE FUNCTION public.redeem_loyalty_points(p_points integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  remaining integer;
  uid       text := public.app_uid();
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'You must be signed in.';
  END IF;
  IF p_points IS NULL OR p_points <= 0 THEN
    RAISE EXCEPTION 'Points to redeem must be positive.';
  END IF;

  UPDATE profiles
  SET loyalty_points = loyalty_points - p_points
  WHERE id = uid AND loyalty_points >= p_points
  RETURNING loyalty_points INTO remaining;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Not enough points.';
  END IF;

  RETURN remaining;
END;
$$;

-- Owner only, unpaid only, within five minutes. The row is kept and marked
-- cancelled rather than deleted, so admin stats stay accurate.
CREATE OR REPLACE FUNCTION public.cancel_order(p_order_id text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  o   orders;
  uid text := public.app_uid();
BEGIN
  SELECT * INTO o FROM orders WHERE id = p_order_id FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found.';
  END IF;
  IF uid IS NULL OR o.user_id IS DISTINCT FROM uid THEN
    RAISE EXCEPTION 'Unauthorized.';
  END IF;
  IF o.payment_status = 'paid' THEN
    RAISE EXCEPTION 'Paid orders cannot be cancelled.';
  END IF;
  IF now() - o.created_at > interval '5 minutes' THEN
    RAISE EXCEPTION 'Cancellation window expired (5 minutes).';
  END IF;

  UPDATE orders SET status = 'cancelled' WHERE id = p_order_id;
END;
$$;

-- ============================================================================
-- Row Level Security
--
-- The Supabase anon key ships to the browser, so anyone can query the REST API
-- directly. RLS is not defence in depth here — it is the access control.
--
-- RLS on with no matching policy means deny, so a table added without policies
-- is inaccessible rather than open. That is the intended failure direction.
-- ============================================================================

ALTER TABLE "profiles"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "orders"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reviews"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "deals"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "updates"     ENABLE ROW LEVEL SECURITY;

-- profiles ------------------------------------------------------------------
-- Rows are created by /api/auth/session with the service role, so there is
-- deliberately no client insert policy.
CREATE POLICY "profiles: read own" ON "profiles"
  FOR SELECT USING (id = public.app_uid());

CREATE POLICY "profiles: admin reads all" ON "profiles"
  FOR SELECT USING (public.is_admin());

-- role and loyalty_points are guarded by profiles_guard_columns above.
CREATE POLICY "profiles: update own" ON "profiles"
  FOR UPDATE USING (id = public.app_uid())
  WITH CHECK (id = public.app_uid());

CREATE POLICY "profiles: admin writes all" ON "profiles"
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- products ------------------------------------------------------------------
-- `active OR is_admin()` gives admins visibility of unpublished products
-- through the same query the storefront uses.
CREATE POLICY "products: public reads active" ON "products"
  FOR SELECT USING (active OR public.is_admin());

CREATE POLICY "products: admin writes" ON "products"
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- orders --------------------------------------------------------------------
-- There is deliberately no customer UPDATE policy: customers change an order
-- through cancel_order(), which enforces owner/unpaid/5-minutes. A general
-- update policy would let a customer set their own payment_status.
CREATE POLICY "orders: read own" ON "orders"
  FOR SELECT USING (user_id = public.app_uid());

CREATE POLICY "orders: create own" ON "orders"
  FOR INSERT WITH CHECK (
    user_id = public.app_uid()
    -- Pins the opening state. A client cannot open an order that claims to be
    -- paid, nor one that pre-claims points, nor one posing as an admin road sale.
    AND status = 'pending'
    AND payment_status = 'unpaid'
    AND source = 'storefront'
    AND points_awarded = false
  );

CREATE POLICY "orders: admin full access" ON "orders"
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- order_items ---------------------------------------------------------------
-- Access derives from the parent order rather than being duplicated.
CREATE POLICY "order_items: read own" ON "order_items"
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM orders o WHERE o.id = order_id AND o.user_id = public.app_uid())
  );

CREATE POLICY "order_items: create for own order" ON "order_items"
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM orders o WHERE o.id = order_id AND o.user_id = public.app_uid())
  );

CREATE POLICY "order_items: admin full access" ON "order_items"
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- reviews -------------------------------------------------------------------
-- Public read; the author owns their own row. Insert requires a signed-in user,
-- so ratings cannot be trivially inflated.
CREATE POLICY "reviews: public read" ON "reviews"
  FOR SELECT USING (true);

CREATE POLICY "reviews: create own" ON "reviews"
  FOR INSERT WITH CHECK (user_id = public.app_uid());

CREATE POLICY "reviews: update own" ON "reviews"
  FOR UPDATE USING (user_id = public.app_uid()) WITH CHECK (user_id = public.app_uid());

CREATE POLICY "reviews: delete own" ON "reviews"
  FOR DELETE USING (user_id = public.app_uid());

CREATE POLICY "reviews: admin full access" ON "reviews"
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- deals ---------------------------------------------------------------------
CREATE POLICY "deals: public reads active" ON "deals"
  FOR SELECT USING (active OR public.is_admin());

CREATE POLICY "deals: admin writes" ON "deals"
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- updates -------------------------------------------------------------------
CREATE POLICY "updates: public read" ON "updates"
  FOR SELECT USING (true);

CREATE POLICY "updates: admin writes" ON "updates"
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ============================================================================
-- Storage
--
-- Three public-read buckets. `public` means anyone with the URL can fetch the
-- object, which is what a storefront product photo is for. Writes are what is
-- restricted.
--
--   product-images  <product-slug>/<timestamp>-<random>.<ext>   admin write
--   deal-images     <timestamp>-<random>.<ext>                  admin write
--   avatars         <firebase-uid>/<timestamp>-<random>.<ext>   owner write
--
-- file_size_limit and allowed_mime_types mean Storage itself refuses an
-- oversized or non-image upload. The checks in lib/supabase/storage.ts exist to
-- name the offending file, not to provide the guarantee.
-- ============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('product-images', 'product-images', true, 5242880,
   ARRAY['image/jpeg','image/png','image/webp','image/avif','image/gif']),
  ('deal-images', 'deal-images', true, 5242880,
   ARRAY['image/jpeg','image/png','image/webp','image/avif','image/gif']),
  ('avatars', 'avatars', true, 2097152,
   ARRAY['image/jpeg','image/png','image/webp','image/avif'])
ON CONFLICT (id) DO UPDATE
  SET public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

DROP POLICY IF EXISTS "kelmon buckets: public read" ON storage.objects;
DROP POLICY IF EXISTS "kelmon images: admin write"  ON storage.objects;
DROP POLICY IF EXISTS "kelmon images: admin update" ON storage.objects;
DROP POLICY IF EXISTS "kelmon images: admin delete" ON storage.objects;
DROP POLICY IF EXISTS "avatars: owner write"        ON storage.objects;
DROP POLICY IF EXISTS "avatars: owner update"       ON storage.objects;
DROP POLICY IF EXISTS "avatars: owner delete"       ON storage.objects;

CREATE POLICY "kelmon buckets: public read" ON storage.objects
  FOR SELECT USING (bucket_id IN ('product-images', 'deal-images', 'avatars'));

CREATE POLICY "kelmon images: admin write" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id IN ('product-images', 'deal-images') AND public.is_admin()
  );

CREATE POLICY "kelmon images: admin update" ON storage.objects
  FOR UPDATE USING (
    bucket_id IN ('product-images', 'deal-images') AND public.is_admin()
  );

CREATE POLICY "kelmon images: admin delete" ON storage.objects
  FOR DELETE USING (
    bucket_id IN ('product-images', 'deal-images') AND public.is_admin()
  );

-- storage.foldername(name) splits the object path; [1] is the top folder, which
-- must be the caller's own UID — so nobody can overwrite another user's photo.
CREATE POLICY "avatars: owner write" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'avatars'
    AND public.app_uid() IS NOT NULL
    AND (storage.foldername(name))[1] = public.app_uid()
  );

CREATE POLICY "avatars: owner update" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'avatars'
    AND public.app_uid() IS NOT NULL
    AND (storage.foldername(name))[1] = public.app_uid()
  );

CREATE POLICY "avatars: owner delete" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'avatars'
    AND (
      public.is_admin()
      OR (public.app_uid() IS NOT NULL AND (storage.foldername(name))[1] = public.app_uid())
    )
  );
